spring.application.name=sistema-gestao-consultas-backend

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sistemaodonto
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

security.jwt.secret=chave-super-segura-odonto-flow-2026-jwt-assinatura-32-caracteres
security.jwt.expiration-ms=86400000
